### ISSUE TITLE
False result for temperature under 0°C

### ISSUE THREAD

**Issue by ckuehnel** [tectiv3/am2315-lua#1]
For AM2315 the MSB of the temperature is set for negative temperatures.
Masking this bit and multiplication of the result by -1 gives the right value in this case.

For upload I had to change from .lua to .txt. Rename it before use.
[am2315.txt](https://github.com/tectiv3/am2315-lua/files/620460/am2315.txt)

**Comment by tectiv3** [comment]
It has been fixed by @loblik
